### ISSUE TITLE
pkg_resources.DistributionNotFound: monasca-agent

### ISSUE THREAD

**Issue by hawkwang** [hpcloud-mon/monasca-installer#28]
I encounter to execute this installer with following error messages:

TASK: [Run monasca-collector info to find any problems on the host] *********** 
<10.103.13.196> 
<10.103.13.196> 
<10.103.13.196> PubkeyAuthentication=no ConnectTimeout=10 GSSAPIAuthentication=no User=root ControlPath=/home/hawkwang/.ansible/cp/ansible-ssh-%h-%p-%r ControlMaster=auto Port=22 ControlPersist=60s
<10.103.15.94> 
<10.103.15.94> 
<10.103.15.94> PubkeyAuthentication=no ConnectTimeout=10 GSSAPIAuthentication=no User=root ControlPath=/home/hawkwang/.ansible/cp/ansible-ssh-%h-%p-%r ControlMaster=auto Port=22 ControlPersist=60s
<10.103.13.196> 
<10.103.15.94> 
<10.103.13.196> PubkeyAuthentication=no ConnectTimeout=10 GSSAPIAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1425090256.88-82100347983650/command; rm -rf /root/.ansible/tmp/ansible-tmp-1425090256.88-82100347983650/ >/dev/null 2>&1' User=root ControlPath=/home/hawkwang/.ansible/cp/ansible-ssh-%h-%p-%r ControlMaster=auto Port=22 ControlPersist=60s
<10.103.15.94> PubkeyAuthentication=no ConnectTimeout=10 GSSAPIAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1425090256.91-123757132934374/command; rm -rf /root/.ansible/tmp/ansible-tmp-1425090256.91-123757132934374/ >/dev/null 2>&1' User=root ControlPath=/home/hawkwang/.ansible/cp/ansible-ssh-%h-%p-%r ControlMaster=auto Port=22 ControlPersist=60s
failed: [10.103.13.196] => {"changed": true, "cmd": ["monasca-collector", "info"], "delta": "0:00:00.234708", "end": "2015-02-28 10:24:17.310516", "rc": 1, "start": "2015-02-28 10:24:17.075808", "warnings": []}
stderr: /usr/local/lib/python2.7/dist-packages/monasca_agent/common/config.py:4: UserWarning: Module _yaml was already imported from /usr/lib/python2.7/dist-packages/_yaml.so, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources
Traceback (most recent call last):
  File "/usr/local/bin/monasca-collector", line 6, in <module>
    from monasca_agent.collector.daemon import main
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/collector/daemon.py", line 12, in <module>
    import checks.collector
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/collector/checks/__init__.py", line 1, in <module>
    from check import AgentCheck
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/collector/checks/check.py", line 19, in <module>
    import monasca_agent.common.check_status as check_status
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/common/check_status.py", line 104, in <module>
    class AgentStatus(object):
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/common/check_status.py", line 111, in AgentStatus
    agent_config = config.Config()
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/common/singleton.py", line 8, in __call__
    cls.instance = super(Singleton, cls).__call__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/common/config.py", line 41, in __init__
    self._read_config()
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/common/config.py", line 69, in _read_config
    self._config = self._retrieve_sections(file_config)
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/common/config.py", line 83, in _retrieve_sections
    'version': self.get_version(),
  File "/usr/local/lib/python2.7/dist-packages/monasca_agent/common/config.py", line 61, in get_version
    return pkg_resources.require("monasca-agent")[0].version
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: monasca-agent

And I checked that the monasca-agent is installed well.

**Comment by craigbr** [comment]
Hi. We need a little more information to help you out. Can you send the output of:

pip list | grep monasca-agent

And tell us exactly what operating system you are trying to run the agent on?
