### ISSUE TITLE
Installing monasca on standalone Ubuntu system without openstack

### ISSUE THREAD

**Issue by sourav82** [hpcloud-mon/monasca-installer#35]
Hi,

I was trying to install monasca on standalone Ubuntu system and used below hosts file -

``` bash
[mysql_host]
monasca

[monasca_workers]
monasca

[monasca_master]
monasca

[monasca:children]
monasca_master
monasca_workers

[keystone_host]
monasca

[devstack]
one

[agent:children]
monasca
devstack
```

But getting below errors -

failed: [monasca] => {"failed": true}
msg: Failed to find required executable virtualenv

FATAL: all hosts have already failed -- aborting

Does it need openstack virtual environment or is there any way I can set it up on standalone Ubuntu?

Regards

**Comment by sourav82** [comment]
After installing virtualenc, now I'm getting below errors -

``` bash
failed: [monasca] => {"changed": true, "cmd": ["/opt/monasca/bin/python", "/usr/local/bin/create_monasca_service.py"], "delta": "0:00:00.453132", "end": "2015-11-04 11:26:33.918875", "rc": 1, "start": "2015-11-04 11:26:33.465743", "warnings": []}
stderr: If token is not given, keystone_admin and keystone_admin_password must be given
Traceback (most recent call last):
  File "/usr/local/bin/create_monasca_service.py", line 167, in <module>
    sys.exit(main())
  File "/usr/local/bin/create_monasca_service.py", line 151, in main
    if not add_tenants(key, tenants):
  File "/usr/local/bin/create_monasca_service.py", line 43, in add_tenants
    if not get_tenant(key, tenant_name):
  File "/usr/local/bin/create_monasca_service.py", line 33, in get_tenant
    for tenant in key.tenants.list():
  File "/opt/monasca/local/lib/python2.7/site-packages/keystoneclient/v2_0/tenants.py", line 123, in list
    tenant_list = self._list('/tenants%s' % query, 'tenants')
  File "/opt/monasca/local/lib/python2.7/site-packages/keystoneclient/base.py", line 124, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/opt/monasca/local/lib/python2.7/site-packages/keystoneclient/adapter.py", line 170, in get
    return self.request(url, 'GET', **kwargs)
  File "/opt/monasca/local/lib/python2.7/site-packages/keystoneclient/adapter.py", line 206, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/opt/monasca/local/lib/python2.7/site-packages/keystoneclient/adapter.py", line 95, in request
    return self.session.request(url, method, **kwargs)
  File "/opt/monasca/local/lib/python2.7/site-packages/keystoneclient/utils.py", line 337, in inner
    return func(*args, **kwargs)
  File "/opt/monasca/local/lib/python2.7/site-packages/keystoneclient/session.py", line 309, in request
    raise exceptions.AuthorizationFailure(msg)
keystoneclient.exceptions.AuthorizationFailure: No valid authentication is available

FATAL: all hosts have already failed -- aborting
```

Using below hosts file -

``` bash
[mysql_host]
monasca

[multi-service]
three
four

[monasca_workers]
monasca

[monasca_master]
monasca

[monasca:children]
monasca_master
monasca_workers

[keystone_host]
172.17.0.37

[devstack]
one

[agent:children]
monasca
devstack
multi-service
```

172.17.0.37 is the ip address of a docker container where keystone is running on port 35357.

Regards
